apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fexxe4q08-go 
  janus-idp.io/tekton: fexxe4q08-go
  backstage.io/kubernetes-id: fexxe4q08-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fexxe4q08-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml