apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fexxe4q08-go-gitops
  description: This is GitOps manifest for fexxe4q08-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=fexxe4q08-go
    backstage.io/kubernetes-id: fexxe4q08-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fexxe4q08-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fexxe4q08-go
